export const TYPE = {
  USER_SEARCH: "USER_SEARCH",
  USER_SEARCH_SUCCESS: "USER_SEARCH_SUCCESS",

  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_LOADING: "SET_LOADING",
  REPO_SEARCH: "REPO_SEARCH",
  ORGANIZATION_SEARCH: "ORGANIZATION_SEARCH",
};
